name: designer_and_artist
description: "A new Flutter project."

publish_to: 'none' 


version: 1.1.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  liquid_swipe: ^3.1.0
  flutter_screenutil: ^5.9.3
  keyboard_actions: ^4.2.0
  iconsax_plus: ^1.0.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.0
  launch_review: ^3.0.1
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  webview_flutter: ^4.10.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  flutter_launcher_icons: ^0.14.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Billy
      fonts:
        - asset: assets/font.ttf  
