// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvr2zuQAE3sNJuGVDzvHagPvRXTyIn9JM',
    appId: '1:182007843901:web:d6079ae866d1f479a42e54',
    messagingSenderId: '182007843901',
    projectId: 'design-and-art-8e1d6',
    authDomain: 'design-and-art-8e1d6.firebaseapp.com',
    storageBucket: 'design-and-art-8e1d6.appspot.com',
    measurementId: 'G-CJL8QF53DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpVMe9nlhqIcXqIKS7T-Ftnnyr8-rtz8',
    appId: '1:182007843901:android:62e8393dd2b9c036a42e54',
    messagingSenderId: '182007843901',
    projectId: 'design-and-art-8e1d6',
    storageBucket: 'design-and-art-8e1d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTh9ODwJylF38ceZ6T155eMkO866-xc0',
    appId: '1:182007843901:ios:da7e609b12466a57a42e54',
    messagingSenderId: '182007843901',
    projectId: 'design-and-art-8e1d6',
    storageBucket: 'design-and-art-8e1d6.appspot.com',
    iosBundleId: 'com.colorcode.WV40Aplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTh9ODwJylF38ceZ6T155eMkO866-xc0',
    appId: '1:182007843901:ios:00a09d2c489d3181a42e54',
    messagingSenderId: '182007843901',
    projectId: 'design-and-art-8e1d6',
    storageBucket: 'design-and-art-8e1d6.appspot.com',
    iosBundleId: 'com.example.designerAndArtist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvr2zuQAE3sNJuGVDzvHagPvRXTyIn9JM',
    appId: '1:182007843901:web:a046479795be89c8a42e54',
    messagingSenderId: '182007843901',
    projectId: 'design-and-art-8e1d6',
    authDomain: 'design-and-art-8e1d6.firebaseapp.com',
    storageBucket: 'design-and-art-8e1d6.appspot.com',
    measurementId: 'G-HH618KGRY5',
  );
}
